version: 2.1

default_docker: &defaults
  docker:
    - image: circleci/node:13.8.0
jobs:
  build:
    <<: *defaults
    steps:
      - checkout
      - run: npm i
      - save_cache:
        key: "npm-packages"
        paths:
          - /src/node
      - run: npm run lint
  test:
    <<: *defaults
    steps:
      - checkout
      - restore_cache:
        keys: 
          - "npm-packages"
      - run: npm i
      - npm run test
  analyze:
    <<: *defaults
    steps:
      - checkout
      - restore_cache:
        keys:
          - "npm-packages"
      - run: npm audit

workflows:
  custom_workflow:
    jobs:
      - build
      - test:
          reqires:
            - build
      - analyze:
          requires:
            - test